const Images = [
  {image: require('../assets/banners/image1.png')},
  {image: require('../assets/banners/image2.png')},
  {image: require('../assets/banners/image3.png')},
  {image: require('../assets/banners/image4.png')},
];

export const data = [
  {
    id: '1',
    coordinate: {
      latitude: -7.546839,
      longitude: 112.226479,
    },
    title: 'Budidaya Padi',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[0].image,
    rating: 4,
    reviews: 99,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['pertanian', 'sawah', 'beras'],
  },
  {
    id: '2',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    title: 'Budidaya Jagung',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[1].image,
    rating: 5,
    reviews: 102,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '3',
    coordinate: {
      latitude: 22.6281662,
      longitude: 88.4410113,
    },
    title: 'Budidaya tebu',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[2].image,
    rating: 3,
    reviews: 220,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '4',
    coordinate: {
      latitude: 22.6341137,
      longitude: 88.4497463,
    },
    title: 'Budidaya Kedelai',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[3].image,
    rating: 4,
    reviews: 48,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
  {
    id: '5',
    coordinate: {
      latitude: 22.6292757,
      longitude: 88.444781,
    },
    title: 'Budidaya Padi',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[0].image,
    rating: 4,
    reviews: 178,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '6',
    coordinate: {
      latitude: 22.6293867,
      longitude: 88.4354486,
    },
    title: 'Budidaya Jagung',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[1].image,
    rating: 4,
    reviews: 99,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Hotel', 'Dineout'],
  },
  {
    id: '7',
    coordinate: {
      latitude: 22.6345648,
      longitude: 88.4377279,
    },
    title: 'Budidaya Kedelai',
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque est metus, gravida vel ex volutpat, posuere euismod tortor. Pellentesque tincidunt, mi ac varius blandit, quam orci dignissim risus, vitae rutrum orci urna ut neque.
      
      Pellentesque condimentum ut libero id blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.`,
    image: Images[3].image,
    rating: 5,
    reviews: 102,
    namapetani: 'Yusuf Mukarom',
    kota: 'Jombang',
    provinsi: 'Jawa Timur',
    bedge: 'Petani Baik',
    tenor : '6 bulan',
    bulantenor: '10 November - 9 Mei  2020',
    ditutupdalam: '12 Hari',
    keuntungan: '12%',
    luaslahan: '1.3 Ha',
    minimalinvestasi: 'Rp100.000',
    tercapai: 'Rp40.000.000',
    target: 'Rp134.000.000',
    categories: ['Restaurant', 'Fastfood Center', 'Snacks Corner'],
  },
];
