const Images = [
    {image: require('../assets/banners/image1.png')},
    {image: require('../assets/banners/image2.png')},
    {image: require('../assets/banners/image3.png')},
    {image: require('../assets/banners/image4.png')},
  ];
export default Notifications = [
    {
        id: 1,
        title: 'Budidaya Padi - Jombang',
        petani: 'Yusuf Mukharom.',
        bedge: 'Petani Baik',
        hitunganmundur: '5 Hari',
        totalinvestasi: 'Rp. 100,000',
        keuntungan: '10%',
        images: require('../assets/banners/image1.png'),

    },
    {
        id: 2,
        title: 'Budidaya Padi - Jombang',
        petani: 'Yusuf Mukharom.',
        bedge: 'Petani Baik',
        hitunganmundur: '5 Hari',
        totalinvestasi: 'Rp. 100,000',
        keuntungan: '10%',
        images: require('../assets/banners/image1.png'),
    },
    {
        id: 3,
        title: 'Budidaya Jagung - Jombang',
        petani: 'Yusuf Mukharom.',
        bedge: 'Petani Baik',
        hitunganmundur: '5 Hari',
        totalinvestasi: 'Rp. 100,000',
        keuntungan: '10%',
        images: require('../assets/banners/image2.png'),
    },
    {
        id: 4,
        title: 'Budidaya Padi - Jombang',
        petani: 'Yusuf Mukharom.',
        bedge: 'Petani Baik',
        hitunganmundur: '5 Hari',
        totalinvestasi: 'Rp. 100,000',
        keuntungan: '10%',
        images: require('../assets/banners/image1.png'),
    },
    {
        id: 5,
        title: 'Budidaya Padi - Jombang',
        petani: 'Yusuf Mukharom.',
        bedge: 'Petani Baik',
        hitunganmundur: '5 Hari',
        totalinvestasi: 'Rp. 100,000',
        keuntungan: '10%',
        images: require('../assets/banners/image1.png'),
    },  
];